module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "subject-case": [2, "always", ["sentence-case", "lower-case", "upper-case"]],
    "subject-empty": [2, "never"],
    "type-empty": [2, "never"],
    "type-enum": [
      2,
      "always",
      [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "spike",
        "style",
        "test",
        "security",
      ],
    ],
    "scope-enum": [
      1,
      "always",
      [
        "ai",
        "analysis",
        "changes",
        "checker",
        "config",
        "core",
        "docs",
        "formatting",
        "format",
        "reformat",
        "rules",
        "safety",
        "settings",
        "style",
        "test",
        "ui",
        "word",
      ],
    ],
  },
};
