/**
 * Public surface of the indexed consistency engine.
 *
 * Import from here rather than from the internals. The internal layout is a
 * detail of this engine; the contract callers depend on is the consent gate,
 * the pipeline entry point, and the report shape.
 *
 * Per ADR-0052 this engine is the single sanctioned exception to
 * deterministic-first. It is never called from the typing path or the
 * observer.
 */

export {
  CONSISTENCY_ACTIONABLE_CONFIDENCE,
  CONSISTENCY_DEFAULT_MAX_PER_SUBJECT,
  CONSISTENCY_DEFAULT_MAX_ADJUDICATIONS,
  CONSISTENCY_CONSENT_ERROR,
  CONSISTENCY_CHECK_IDS,
  CONSISTENCY_CHECKS,
  ConsistencyCheckIdSchema,
  ConsistencyAdjudicationSchema,
  ConsistencyCandidateSchema,
  ConsistencyCoverageSchema,
  ConsistencyDocumentSchema,
  ConsistencyIssueSchema,
  ConsistencyProgressSchema,
  ConsistencyReportSchema,
  ConsistencyReviewRequestSchema,
  ConsistencyStatementSchema,
  ConsistencyVerdictSchema,
  ClaimClassSchema,
  AdoptionStatusSchema,
  PartyRefSchema,
  CanonicalPredicateSchema,
  DateValueSchema,
  TemporalContextSchema,
  ProgrammeTypeSchema,
  ProgrammeContextSchema,
  DelayContextSchema,
  QuantumBasisSchema,
  QuantumContextSchema,
  CausationContextSchema,
  ResponsibilityContextSchema,
  ContractualBasisSchema,
  EvidenceBasisSchema,
  ClaimValueSchema,
  ClaimScopeSchema,
  ClaimModalitySchema,
  QualifierSchema,
  AssertionStrengthSchema,
  ScenarioTypeSchema,
  ScenarioContextSchema,
  ExtractionPassSchema,
  ExtractionMetadataSchema,
  ExpertReportClaimSchema,
  EvidenceAnchorSchema,
  QuarantinedClaimSchema,
  EvidenceRegistrySchema,
  DecisionSubjectSchema,
  DOutcomeSchema,
  EvaluationVectorSchema,
  ConfidenceProfileSchema,
  DecisionQuestionSchema,
  DecisionPlanSchema,
  CONSISTENCY_STORE_VERSION,
  ConsistencyStoreRecordSchema,
  consistencyCheck,
  parseConsistencyReviewRequest,
  type ConsistencyCheckId,
  type ConsistencyCheckDescriptor,
  type ConsistencyAdjudication,
  type ConsistencyCandidate,
  type ConsistencyCoverage,
  type ConsistencyDocument,
  type ConsistencyIssue,
  type ConsistencyProgress,
  type ConsistencyReport,
  type ConsistencyReviewRequest,
  type ConsistencyStatement,
  type ConsistencyVerdict,
  type ClaimClass,
  type AdoptionStatus,
  type PartyRef,
  type CanonicalPredicate,
  type DateValue,
  type TemporalContext,
  type ProgrammeType,
  type ProgrammeContext,
  type DelayContext,
  type QuantumBasis,
  type QuantumContext,
  type CausationContext,
  type ResponsibilityContext,
  type ContractualBasis,
  type EvidenceBasis,
  type ClaimValue,
  type ClaimScope,
  type ClaimModality,
  type Qualifier,
  type AssertionStrength,
  type ScenarioType,
  type ScenarioContext,
  type ExtractionPass,
  type ExtractionMetadata,
  type ExpertReportClaim,
  type EvidenceAnchor,
  type QuarantinedClaim,
  type EvidenceRegistry,
  type DecisionSubject,
  type DOutcome,
  type EvaluationVector,
  type ConfidenceProfile,
  type DecisionQuestion,
  type DecisionPlan,
  type ConsistencyStoreRecord,
  type ConsistencyStore,
} from "./contracts";

export {
  ConsistencyRunCancelled,
  previewStatements,
  runConsistencyReview,
  segmentDocument,
  type ConsistencyRunOptions,
} from "./indexedEngine";

export {
  buildAliasIndex,
  collectAliasEntries,
  normaliseClaims,
  partyAliases,
  type AliasEntry,
  type AliasIndex,
  type NormalisedClaim,
  type NormalisedDate,
} from "./normalisation";
export {
  baseUnit,
  compatibleUnits,
  currencyCode,
  normaliseDate,
  normaliseValue,
  parseDecimal,
  parseDurationDays,
  quantityKey,
  toBaseUnit,
  unitDimension,
} from "./normalisation";
export { buildIndices, type ConsistencyIndices } from "./indices";
export {
  capSubjectClaims,
  evidenceIdsFor,
  makeCandidate,
  retrieveCandidates,
  retrieveC1,
  retrieveC2,
  retrieveC3,
  retrieveC4,
  retrieveC5,
  retrieveC6,
  retrieveC7,
  retrieveC8,
  retrieveC9,
  retrieveC10,
  subjectKey,
  type CheckRetrieval,
  type CheckRetriever,
  type RetrievalContext,
} from "./candidates";

export { consistencyCategory, summarizeReport, toFinding, toFindings } from "./bridge";

export {
  collapsedCount,
  groupConsistencyIssues,
  isLocatable,
  issueGroupKey,
  type ConsistencyIssueGroup,
} from "./grouping";

export { buildIssue, buildWhyConfidence, type IssueAnswer, type IssueInput } from "./issues";

export {
  buildPreflight,
  redactionListFor,
  type ConsistencyPreflight,
  type PreflightInput,
} from "./preflight";

export {
  CONSISTENCY_STORE_TTL_DAYS,
  CONSISTENCY_STORE_TTL_MS,
  ConsistencyAuditRecordSchema,
  ConsistencySessionProvenanceSchema,
  ConsistencySessionStore,
  IndexedDbStore,
  MemoryStore,
  buildAuditRecord,
  buildProvenance,
  decryptString,
  deriveDeviceKey,
  encryptString,
  evidenceStillValid,
  generateDataKey,
  isExpired,
  unwrapDataKey,
  wrapDataKey,
  type ConsistencyAuditRecord,
  type ConsistencySessionProvenance,
  type EncryptedPayload,
  type ProvenanceInput,
} from "./persistence";
